export * from "./LogoIcon";
export * from "./StudentIcon";
export * from "./CalendarIcon";
export * from "./BookIcon";
export * from "./PersonIcon";
export * from "./SettingsIcon";
export * from "./PlusIcon";
export * from "./ListIcon";
export * from "./TargetArrowIcon";
